Drop support for python 3.8 (#1752)
* Drop support for python 3.8

Python 3.8 reached _end-of-life_ status on 2024-10-07.  
https://devguide.python.org/versions/#unsupported-versions  

Even in the beta version (2.0.0b25), it is breaking because some functions  
use type annotations (e.g., `list[int]`), which are only supported in  
version 3.9 or later.

Stacktrace:
```
Python 3.8.20 (default, Jan 13 2025, 14:24:56) 
[GCC 14.2.1 20240910] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import basedosdados
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/bd-test/.venv/lib/python3.8/site-packages/basedosdados/__init__.py", line 14, in <module>
    from basedosdados.backend import Backend
  File "/tmp/bd-test/.venv/lib/python3.8/site-packages/basedosdados/backend.py", line 36, in <module>
    class Backend(metaclass=SingletonMeta):
  File "/tmp/bd-test/.venv/lib/python3.8/site-packages/basedosdados/backend.py", line 233, in Backend
    def search(self, q: str = None, page: int = 1, page_size: int = 10) -> list[dict]:
TypeError: 'type' object is not subscriptable
```

With this change, attempting to install the package using Python 3.8  
will result in an error.